
/* Drop Tables */

DROP TABLE SOCAR.NOTICE_IMG CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE AD CASCADE CONSTRAINTS;
DROP TABLE CANC CASCADE CONSTRAINTS;
DROP TABLE CAR_WASTE CASCADE CONSTRAINTS;
DROP TABLE COU_USE CASCADE CONSTRAINTS;
DROP TABLE PANALTY_ACT CASCADE CONSTRAINTS;
DROP TABLE RENT_E CASCADE CONSTRAINTS;
DROP TABLE RENT_EX CASCADE CONSTRAINTS;
DROP TABLE RENT_S CASCADE CONSTRAINTS;
DROP TABLE RESERVE CASCADE CONSTRAINTS;
DROP TABLE CAR_ISSUE CASCADE CONSTRAINTS;
DROP TABLE COU_USECAR CASCADE CONSTRAINTS;
DROP TABLE CAR CASCADE CONSTRAINTS;
DROP TABLE CARD CASCADE CONSTRAINTS;
DROP TABLE CAR_MODEL CASCADE CONSTRAINTS;
DROP TABLE COU_ISSUE CASCADE CONSTRAINTS;
DROP TABLE COU_CREATE CASCADE CONSTRAINTS;
DROP TABLE COU_RESTRICTION CASCADE CONSTRAINTS;
DROP TABLE COUPON CASCADE CONSTRAINTS;
DROP TABLE DEPT CASCADE CONSTRAINTS;
DROP TABLE KEY_C_SEND CASCADE CONSTRAINTS;
DROP TABLE KEY_C_RQ CASCADE CONSTRAINTS;
DROP TABLE MEMBERSHIP CASCADE CONSTRAINTS;
DROP TABLE MEM CASCADE CONSTRAINTS;
DROP TABLE PANALTY CASCADE CONSTRAINTS;
DROP TABLE RQC_DIS CASCADE CONSTRAINTS;
DROP TABLE RQC_LIKE CASCADE CONSTRAINTS;
DROP TABLE RQL_DIS CASCADE CONSTRAINTS;
DROP TABLE RQL_LIKE CASCADE CONSTRAINTS;
DROP TABLE RQ_CAR CASCADE CONSTRAINTS;
DROP TABLE RQ_LOC CASCADE CONSTRAINTS;
DROP TABLE SIMPLE_MEM CASCADE CONSTRAINTS;
DROP TABLE SO_ZONE CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE AD
(
	AD_ID varchar2(15) NOT NULL,
	DEPT_NO varchar2(10) NOT NULL,
	AD_NAME varchar2(10) NOT NULL,
	AD_PWD varchar2(15) NOT NULL,
	AD_REGIDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (AD_ID)
);


CREATE TABLE CANC
(
	RES_CODE varchar2(15) NOT NULL,
	CANC_DATE date DEFAULT SYSDATE NOT NULL,
	CANC_PRICE number NOT NULL,
	PRIMARY KEY (RES_CODE)
);


CREATE TABLE CAR
(
	CAR_NAME_CODE varchar2(15) NOT NULL,
	CAR_TYPE_CODE varchar2(15) NOT NULL,
	CAR_NAME varchar2(15) NOT NULL,
	CAR_IMG varchar2(150) NOT NULL,
	CAR_DESC nvarchar2(500) NOT NULL,
	CAR_LAND_PRICE number NOT NULL,
	CAR_JEJU_PRICE number NOT NULL,
	CAR_PRICE_SO_WD number NOT NULL,
	CAR_PRICE_SO_WE number NOT NULL,
	CAR_DRIVE_PRICE number NOT NULL,
	CAR_COM varchar2(50) NOT NULL,
	CAR_FUEL varchar2(10) NOT NULL,
	CAR_TRANS varchar2(15) NOT NULL,
	CAR_MAX_PER number(2,0) NOT NULL,
	PRIMARY KEY (CAR_NAME_CODE)
);


CREATE TABLE CARD
(
	CARD_CODE varchar2(15) NOT NULL,
	SMEM_ID varchar2(40) NOT NULL,
	CARD_EXPDATE date NOT NULL,
	-- 법인은 'B'
	-- 개인은 'P'
	CARD_TYPE varchar2(1) NOT NULL,
	CARD_BIRTH date NOT NULL,
	CARD_PWD number NOT NULL,
	CARD_CREATEDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (CARD_CODE)
);


CREATE TABLE CAR_ISSUE
(
	CAR_I_CODE varchar2(15) NOT NULL,
	CAR_NAME_CODE varchar2(15) NOT NULL,
	SOZ_CODE varchar2(15) NOT NULL,
	CAR_I_DATE date DEFAULT SYSDATE NOT NULL,
	CAR_I_NUM varchar2(9) NOT NULL,
	CAR_I_SAFE_OPTION varchar2(100) NOT NULL,
	CAR_I_ADD_OPTION varchar2(100) NOT NULL,
	CAR_NICK varchar2(14) NOT NULL,
	PRIMARY KEY (CAR_I_CODE)
);


CREATE TABLE CAR_MODEL
(
	CAR_TYPE_CODE varchar2(15) NOT NULL,
	CAR_TYPE varchar2(15) NOT NULL,
	-- 손해 면책부담금 최대 30만원 선택 중 
	-- 1시간 기준
	CAR_INSURANCE_ONE_HOUR number NOT NULL,
	-- 손해 면책부담금 최대 30만원 선택 중 
	-- 1일 기준
	CAR_INSURANCE_ONE_DAY number NOT NULL,
	-- 손해 면책부담금 최대 70만원 선택 중 
	-- 1시간 기준
	CAR_INSURANCE_TWO_HOUR number NOT NULL,
	-- 손해 면책부담금 최대 70만원 선택 중 
	-- 1일 기준
	CAR_INSURANCE_TWO_DAY number NOT NULL,
	PRIMARY KEY (CAR_TYPE_CODE)
);


CREATE TABLE CAR_WASTE
(
	CAR_I_CODE varchar2(15) NOT NULL,
	CAR_W_DATE date NOT NULL,
	CAR_W_REASON nvarchar2(500) NOT NULL,
	PRIMARY KEY (CAR_I_CODE)
);


CREATE TABLE COUPON
(
	COU_CODE varchar2(15) NOT NULL,
	COU_NAME varchar2(15) NOT NULL,
	COU_DESC varchar2(50) NOT NULL,
	COU_SALE number NOT NULL,
	COU_MINTIME number NOT NULL,
	COU_MAXTIME number NOT NULL,
	COU_MINAGE number(3) NOT NULL,
	COU_MINUSE number(3) NOT NULL,
	COU_EXP date NOT NULL,
	MAX_SALE_PER number(3) NOT NULL,
	-- 'O' , 'X'로 구분
	-- 
	COU_ONLY_NEW varchar2(1) NOT NULL,
	PRIMARY KEY (COU_CODE)
);


CREATE TABLE COU_CREATE
(
	COU_C_CODE varchar2(15) NOT NULL,
	COU_CODE varchar2(15) NOT NULL,
	COU_C_DATE date DEFAULT SYSDATE NOT NULL,
	COU_C_EXPDATE date NOT NULL,
	COU_C_T_START number(4) NOT NULL,
	COU_C_T_END number(4) NOT NULL,
	PRIMARY KEY (COU_C_CODE)
);


CREATE TABLE COU_ISSUE
(
	COU_I_CODE varchar2(20) NOT NULL,
	SMEM_ID varchar2(40) NOT NULL,
	COU_C_CODE varchar2(15) NOT NULL,
	COU_I_DATE date DEFAULT SYSDATE NOT NULL,
	COU_I_E_DATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (COU_I_CODE)
);


CREATE TABLE COU_RESTRICTION
(
	COU_R_CODE varchar2(15) NOT NULL,
	COU_CODE varchar2(15) NOT NULL,
	SOZ_CODE varchar2(15) NOT NULL,
	PRIMARY KEY (COU_R_CODE)
);


CREATE TABLE COU_USE
(
	COU_USE_CODE varchar2(15) NOT NULL,
	COU_I_CODE varchar2(20) NOT NULL,
	RES_CODE varchar2(15) NOT NULL,
	PRIMARY KEY (COU_USE_CODE)
);


CREATE TABLE COU_USECAR
(
	USECAR_CODE varchar2(15) NOT NULL,
	CAR_NAME_CODE varchar2(15) NOT NULL,
	COU_CODE varchar2(15) NOT NULL,
	PRIMARY KEY (USECAR_CODE)
);


CREATE TABLE DEPT
(
	DEPT_NO varchar2(10) NOT NULL,
	DEPT_NAME varchar2(15) NOT NULL,
	DEPT_REGIDATE date DEFAULT SYSDATE NOT NULL,
	DEPT_DESC varchar2(500) NOT NULL,
	PRIMARY KEY (DEPT_NO)
);


CREATE TABLE KEY_C_RQ
(
	KEY_C_RQ_CODE varchar2(15) NOT NULL,
	SMEM_ID varchar2(40) NOT NULL,
	KEY_C_RQ_DATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (KEY_C_RQ_CODE)
);


CREATE TABLE KEY_C_SEND
(
	KEY_C_SEND_CODE varchar2(15) NOT NULL,
	KEY_C_RQ_CODE varchar2(15) NOT NULL,
	KEY_C_SEND_DATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (KEY_C_SEND_CODE)
);


CREATE TABLE MEM
(
	SMEM_ID varchar2(40) NOT NULL,
	MEM_ADDR varchar2(30) NOT NULL,
	MEM_MAINAREA varchar2(20) NOT NULL,
	MEM_BIRTH number NOT NULL,
	-- 남자는 'M'
	-- 여자는 'F'
	MEM_GENDER char(1) NOT NULL,
	MEM_DATE date DEFAULT SYSDATE NOT NULL,
	-- 1N 는 1종 보통
	-- 2N 은 2종 보통
	-- 1B 는 1종 대형
	-- 
	MEM_C_TYPE varchar2(4) NOT NULL,
	-- 
	-- 
	MEM_C_NUM varchar2(20) NOT NULL,
	MEM_C_EXPDATE date NOT NULL,
	-- 
	-- 
	MEM_C_IDATE date NOT NULL,
	PRIMARY KEY (SMEM_ID)
);


CREATE TABLE MEMBERSHIP
(
	MS_CODE varchar2(15) NOT NULL,
	SMEM_ID varchar2(40) NOT NULL UNIQUE,
	MS_CHANGE number NOT NULL,
	PRIMARY KEY (MS_CODE)
);


CREATE TABLE NOTICE
(
	NOT_NO number NOT NULL,
	AD_ID varchar2(15) NOT NULL,
	NOT_TITLE varchar2(100) NOT NULL,
	NOT_CONTENT varchar2(2000) NOT NULL,
	NOT_POSTDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (NOT_NO)
);


CREATE TABLE PANALTY
(
	P_CODE varchar2(15) NOT NULL,
	P_NAME varchar2(20) NOT NULL,
	P_PRICE number NOT NULL,
	PRIMARY KEY (P_CODE)
);


CREATE TABLE PANALTY_ACT
(
	PA_CODE varchar2(15) NOT NULL,
	RES_CODE varchar2(15) NOT NULL,
	P_CODE varchar2(15) NOT NULL,
	PRIMARY KEY (PA_CODE)
);


CREATE TABLE RENT_E
(
	RES_CODE varchar2(15) NOT NULL,
	RENT_E_DATE date DEFAULT SYSDATE NOT NULL,
	RENT_E_ARTICLE nvarchar2(100) NOT NULL,
	RENT_E_KM number NOT NULL,
	RENT_E_HIPASS number NOT NULL,
	RENT_E_PANALTY number NOT NULL,
	RENT_E_ECTPRICE number NOT NULL,
	RENT_E_ECTSALE number NOT NULL,
	PRIMARY KEY (RES_CODE)
);


CREATE TABLE RENT_EX
(
	-- 렌트 최대 두번
	-- 
	RENT_EX_CODE varchar2(15) NOT NULL,
	RES_CODE varchar2(15) NOT NULL,
	RENT_EX_START date NOT NULL,
	RENT_EX_END date NOT NULL,
	PRIMARY KEY (RENT_EX_CODE)
);


CREATE TABLE RENT_S
(
	RES_CODE varchar2(15) NOT NULL,
	RENT_S_DATE date DEFAULT SYSDATE NOT NULL,
	RENT_S_ARTICLE nvarchar2(100) NOT NULL,
	PRIMARY KEY (RES_CODE)
);


CREATE TABLE RESERVE
(
	RES_CODE varchar2(15) NOT NULL,
	SMEM_ID varchar2(40) NOT NULL,
	CAR_I_CODE varchar2(15) NOT NULL,
	CARD_CODE varchar2(15) NOT NULL,
	RES_PRICE number NOT NULL,
	RES_DATE_START date NOT NULL,
	RES_DATE_END date NOT NULL,
	-- 'C' 는 왕복
	-- 'O' 은 편도
	-- 
	RESERVE_TYPE varchar2(1) NOT NULL,
	RES_DATE date DEFAULT SYSDATE NOT NULL,
	RES_INSTYPE nvarchar2(15) NOT NULL,
	-- 쿠폰은 C 멤버십은 M 미적용은 N
	-- 포인트할인일 경우 최대 10000  , 대여요금의 20%까지 가능
	-- 
	-- 
	RES_SALE_TYPE varchar2(1) NOT NULL,
	-- 'N' 은 선택 안함 ,
	--  'T' 는 T머니  ,
	-- 'M' 은 회원카드
	-- 
	RES_CARDKEY varchar2(1) NOT NULL,
	RES_ARTICLE nvarchar2(100) NOT NULL,
	PRIMARY KEY (RES_CODE)
);


CREATE TABLE RQC_DIS
(
	RQC_DIS_CODE varchar2(15) NOT NULL,
	RQC_CODE varchar2(10) NOT NULL,
	SMEM_ID varchar2(40) NOT NULL,
	PRIMARY KEY (RQC_DIS_CODE)
);


CREATE TABLE RQC_LIKE
(
	RQC_LIKE_CODE varchar2(15) NOT NULL,
	RQC_CODE varchar2(10) NOT NULL,
	SMEM_ID varchar2(40) NOT NULL,
	PRIMARY KEY (RQC_LIKE_CODE)
);


CREATE TABLE RQL_DIS
(
	RQL_DIS_CODE varchar2(15) NOT NULL,
	RQL_CODE varchar2(15) NOT NULL,
	SMEM_ID varchar2(40) NOT NULL,
	PRIMARY KEY (RQL_DIS_CODE)
);


CREATE TABLE RQL_LIKE
(
	RQL_LIKE_CODE varchar2(15) NOT NULL,
	RQL_CODE varchar2(15) NOT NULL,
	SMEM_ID varchar2(40) NOT NULL,
	PRIMARY KEY (RQL_LIKE_CODE)
);


CREATE TABLE RQ_CAR
(
	RQC_CODE varchar2(10) NOT NULL,
	RQC_CONTENT varchar2(1000) NOT NULL,
	RQC_LOC varchar2(30) NOT NULL,
	SMEM_ID varchar2(40) NOT NULL,
	PRIMARY KEY (RQC_CODE)
);


CREATE TABLE RQ_LOC
(
	RQL_CODE varchar2(15) NOT NULL,
	RQL_CONTENT varchar2(1000) NOT NULL,
	RQL_LOC varchar2(30) NOT NULL,
	SMEM_ID varchar2(40) NOT NULL,
	PRIMARY KEY (RQL_CODE)
);


CREATE TABLE SIMPLE_MEM
(
	SMEM_ID varchar2(40) NOT NULL,
	SMEM_NAME varchar2(20) NOT NULL,
	SMEM_TEL number NOT NULL,
	SMEM_PWD varchar2(15) NOT NULL,
	SMEM_DATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (SMEM_ID)
);


CREATE TABLE SO_ZONE
(
	SOZ_CODE varchar2(15) NOT NULL,
	SOZ_NAME varchar2(30) NOT NULL,
	SOZ_LOC nvarchar2(30) NOT NULL,
	SOZ_MAXCAR number NOT NULL,
	SOZ_DATE date DEFAULT SYSDATE NOT NULL,
	SOZ_LATITUDE number NOT NULL,
	SOZ_LONGITUDE number NOT NULL,
	PRIMARY KEY (SOZ_CODE)
);


CREATE TABLE SOCAR.NOTICE_IMG
(
	NOT_IMG_CODE number NOT NULL,
	NOT_NO number NOT NULL,
	NOT_IMG_SRC varchar2(100 char) NOT NULL,
	CONSTRAINT SYS_C0011427 PRIMARY KEY (NOT_IMG_CODE)
);



/* Create Foreign Keys */

ALTER TABLE NOTICE
	ADD FOREIGN KEY (AD_ID)
	REFERENCES AD (AD_ID)
;


ALTER TABLE CAR_ISSUE
	ADD FOREIGN KEY (CAR_NAME_CODE)
	REFERENCES CAR (CAR_NAME_CODE)
;


ALTER TABLE COU_USECAR
	ADD FOREIGN KEY (CAR_NAME_CODE)
	REFERENCES CAR (CAR_NAME_CODE)
;


ALTER TABLE RESERVE
	ADD FOREIGN KEY (CARD_CODE)
	REFERENCES CARD (CARD_CODE)
;


ALTER TABLE CAR_WASTE
	ADD FOREIGN KEY (CAR_I_CODE)
	REFERENCES CAR_ISSUE (CAR_I_CODE)
;


ALTER TABLE RESERVE
	ADD FOREIGN KEY (CAR_I_CODE)
	REFERENCES CAR_ISSUE (CAR_I_CODE)
;


ALTER TABLE CAR
	ADD FOREIGN KEY (CAR_TYPE_CODE)
	REFERENCES CAR_MODEL (CAR_TYPE_CODE)
;


ALTER TABLE COU_CREATE
	ADD FOREIGN KEY (COU_CODE)
	REFERENCES COUPON (COU_CODE)
;


ALTER TABLE COU_RESTRICTION
	ADD FOREIGN KEY (COU_CODE)
	REFERENCES COUPON (COU_CODE)
;


ALTER TABLE COU_USECAR
	ADD FOREIGN KEY (COU_CODE)
	REFERENCES COUPON (COU_CODE)
;


ALTER TABLE COU_ISSUE
	ADD FOREIGN KEY (COU_C_CODE)
	REFERENCES COU_CREATE (COU_C_CODE)
;


ALTER TABLE COU_USE
	ADD FOREIGN KEY (COU_I_CODE)
	REFERENCES COU_ISSUE (COU_I_CODE)
;


ALTER TABLE AD
	ADD FOREIGN KEY (DEPT_NO)
	REFERENCES DEPT (DEPT_NO)
;


ALTER TABLE KEY_C_SEND
	ADD FOREIGN KEY (KEY_C_RQ_CODE)
	REFERENCES KEY_C_RQ (KEY_C_RQ_CODE)
;


ALTER TABLE CARD
	ADD FOREIGN KEY (SMEM_ID)
	REFERENCES MEM (SMEM_ID)
;


ALTER TABLE KEY_C_RQ
	ADD FOREIGN KEY (SMEM_ID)
	REFERENCES MEM (SMEM_ID)
;


ALTER TABLE MEMBERSHIP
	ADD FOREIGN KEY (SMEM_ID)
	REFERENCES MEM (SMEM_ID)
;


ALTER TABLE RESERVE
	ADD FOREIGN KEY (SMEM_ID)
	REFERENCES MEM (SMEM_ID)
;


ALTER TABLE SOCAR.NOTICE_IMG
	ADD FOREIGN KEY (NOT_NO)
	REFERENCES NOTICE (NOT_NO)
;


ALTER TABLE PANALTY_ACT
	ADD FOREIGN KEY (P_CODE)
	REFERENCES PANALTY (P_CODE)
;


ALTER TABLE PANALTY_ACT
	ADD FOREIGN KEY (RES_CODE)
	REFERENCES RENT_S (RES_CODE)
;


ALTER TABLE RENT_E
	ADD FOREIGN KEY (RES_CODE)
	REFERENCES RENT_S (RES_CODE)
;


ALTER TABLE RENT_EX
	ADD FOREIGN KEY (RES_CODE)
	REFERENCES RENT_S (RES_CODE)
;


ALTER TABLE CANC
	ADD FOREIGN KEY (RES_CODE)
	REFERENCES RESERVE (RES_CODE)
;


ALTER TABLE COU_USE
	ADD FOREIGN KEY (RES_CODE)
	REFERENCES RESERVE (RES_CODE)
;


ALTER TABLE RENT_S
	ADD FOREIGN KEY (RES_CODE)
	REFERENCES RESERVE (RES_CODE)
;


ALTER TABLE RQC_DIS
	ADD FOREIGN KEY (RQC_CODE)
	REFERENCES RQ_CAR (RQC_CODE)
;


ALTER TABLE RQC_LIKE
	ADD FOREIGN KEY (RQC_CODE)
	REFERENCES RQ_CAR (RQC_CODE)
;


ALTER TABLE RQL_DIS
	ADD FOREIGN KEY (RQL_CODE)
	REFERENCES RQ_LOC (RQL_CODE)
;


ALTER TABLE RQL_LIKE
	ADD FOREIGN KEY (RQL_CODE)
	REFERENCES RQ_LOC (RQL_CODE)
;


ALTER TABLE COU_ISSUE
	ADD FOREIGN KEY (SMEM_ID)
	REFERENCES SIMPLE_MEM (SMEM_ID)
;


ALTER TABLE MEM
	ADD FOREIGN KEY (SMEM_ID)
	REFERENCES SIMPLE_MEM (SMEM_ID)
;


ALTER TABLE RQC_DIS
	ADD FOREIGN KEY (SMEM_ID)
	REFERENCES SIMPLE_MEM (SMEM_ID)
;


ALTER TABLE RQC_LIKE
	ADD FOREIGN KEY (SMEM_ID)
	REFERENCES SIMPLE_MEM (SMEM_ID)
;


ALTER TABLE RQL_DIS
	ADD FOREIGN KEY (SMEM_ID)
	REFERENCES SIMPLE_MEM (SMEM_ID)
;


ALTER TABLE RQL_LIKE
	ADD FOREIGN KEY (SMEM_ID)
	REFERENCES SIMPLE_MEM (SMEM_ID)
;


ALTER TABLE RQ_CAR
	ADD FOREIGN KEY (SMEM_ID)
	REFERENCES SIMPLE_MEM (SMEM_ID)
;


ALTER TABLE RQ_LOC
	ADD FOREIGN KEY (SMEM_ID)
	REFERENCES SIMPLE_MEM (SMEM_ID)
;


ALTER TABLE CAR_ISSUE
	ADD FOREIGN KEY (SOZ_CODE)
	REFERENCES SO_ZONE (SOZ_CODE)
;


ALTER TABLE COU_RESTRICTION
	ADD FOREIGN KEY (SOZ_CODE)
	REFERENCES SO_ZONE (SOZ_CODE)
;



/* Comments */

COMMENT ON COLUMN CARD.CARD_TYPE IS '법인은 ''B''
개인은 ''P''';
COMMENT ON COLUMN CAR_MODEL.CAR_INSURANCE_ONE_HOUR IS '손해 면책부담금 최대 30만원 선택 중 
1시간 기준';
COMMENT ON COLUMN CAR_MODEL.CAR_INSURANCE_ONE_DAY IS '손해 면책부담금 최대 30만원 선택 중 
1일 기준';
COMMENT ON COLUMN CAR_MODEL.CAR_INSURANCE_TWO_HOUR IS '손해 면책부담금 최대 70만원 선택 중 
1시간 기준';
COMMENT ON COLUMN CAR_MODEL.CAR_INSURANCE_TWO_DAY IS '손해 면책부담금 최대 70만원 선택 중 
1일 기준';
COMMENT ON COLUMN COUPON.COU_ONLY_NEW IS '''O'' , ''X''로 구분
';
COMMENT ON COLUMN MEM.MEM_GENDER IS '남자는 ''M''
여자는 ''F''';
COMMENT ON COLUMN MEM.MEM_C_TYPE IS '1N 는 1종 보통
2N 은 2종 보통
1B 는 1종 대형
';
COMMENT ON COLUMN MEM.MEM_C_NUM IS '
';
COMMENT ON COLUMN MEM.MEM_C_IDATE IS '
';
COMMENT ON COLUMN RENT_EX.RENT_EX_CODE IS '렌트 최대 두번
';
COMMENT ON COLUMN RESERVE.RESERVE_TYPE IS '''C'' 는 왕복
''O'' 은 편도
';
COMMENT ON COLUMN RESERVE.RES_SALE_TYPE IS '쿠폰은 C 멤버십은 M 미적용은 N
포인트할인일 경우 최대 10000  , 대여요금의 20%까지 가능

';
COMMENT ON COLUMN RESERVE.RES_CARDKEY IS '''N'' 은 선택 안함 ,
 ''T'' 는 T머니  ,
''M'' 은 회원카드
';



